
const base=window.YESSI_DATA; const KEY='yessiAntipanicoStateV1';
const saved=JSON.parse(localStorage.getItem(KEY)||'{}');
let state={statuses:saved.statuses||{},notes:saved.notes||{},metrics:saved.metrics||[]};
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const toast=t=>{const el=document.getElementById('toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)};
const esc=s=>String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
function navTo(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));document.getElementById('sidebar').classList.remove('open');}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>navTo(b.dataset.view));document.getElementById('menuBtn').onclick=()=>document.getElementById('sidebar').classList.toggle('open');
function status(id){return state.statuses[id]||'Pendiente'}
function reelCard(r){return `<details class="reel"><summary><span class="num">${r.id}</span><div><strong>${esc(r.title)}</strong><div class="muted">${esc(r.theme)} · Fase ${r.phase}</div></div><div class="meta"><span class="tag objective-${r.objective}">${r.objective}</span><span class="tag">${status(r.id)}</span></div></summary><div class="reelbody"><div class="field full"><h4>Hook</h4><p>${esc(r.hook)}</p></div><div class="field"><h4>Contexto</h4><p>${esc(r.context)}</p></div><div class="field"><h4>Esquema de desarrollo</h4><p>${esc(r.development)}</p></div><div class="field"><h4>Tomas</h4><p>${esc(r.shots)}</p></div><div class="field"><h4>CTA</h4><p>${esc(r.cta)}</p></div><div class="field full"><h4>Cómo alimenta la siguiente pieza</h4><p>${esc(r.next)}</p></div><div class="field full"><div class="statusrow"><label>Estado</label><select onchange="setStatus(${r.id},this.value)">${['Pendiente','Guion listo','Grabado','Editado','Publicado'].map(x=>`<option ${status(r.id)===x?'selected':''}>${x}</option>`).join('')}</select></div><textarea class="notes" placeholder="Notas tuyas..." oninput="setNotes(${r.id},this.value)">${esc(state.notes[r.id]||'')}</textarea></div></div></details>`}
window.setStatus=(id,v)=>{state.statuses[id]=v;save();renderAll();toast('Estado guardado')};window.setNotes=(id,v)=>{state.notes[id]=v;save()};
function renderReels(){const q=document.getElementById('search').value.toLowerCase();const o=document.getElementById('objectiveFilter').value;const p=document.getElementById('phaseFilter').value;const arr=base.reels.filter(r=>(!q||JSON.stringify(r).toLowerCase().includes(q))&&(!o||r.objective===o)&&(!p||String(r.phase)===p));document.getElementById('reelsList').innerHTML=arr.map(reelCard).join('')||'<p>No hay resultados.</p>'}
['search','objectiveFilter','phaseFilter'].forEach(id=>document.getElementById(id).addEventListener('input',renderReels));
function renderCalendar(){document.getElementById('calendarGrid').innerHTML=base.schedule.map(s=>{const r=base.reels.find(x=>x.id===s.reelId);return `<div class="day ${r?'':'rest'}"><b>Día ${s.day}</b>${r?`<div class="rtitle"><strong>#${r.id}</strong> ${esc(r.title)}</div><span class="tag objective-${r.objective}">${r.objective}</span>`:'<div class="rtitle">Descanso, stories o grabación</div>'}</div>`}).join('')}
function renderToday(){let idx=Number(localStorage.getItem('yessiDay')||1);idx=Math.max(1,Math.min(90,idx));let item=base.schedule[idx-1],r=base.reels.find(x=>x.id===item.reelId);document.getElementById('todayCard').innerHTML=`<article class="card"><div class="sectionhead"><div><span class="eyebrow">DÍA ACTUAL</span><h2>Día ${idx}</h2></div><div><button onclick="changeDay(-1)">←</button> <button onclick="changeDay(1)">→</button></div></div>${r?reelCard(r):'<h3>Día libre</h3><p>Usa hoy para descansar, responder comentarios o grabar en bloque.</p>'}</article>`}
window.changeDay=d=>{let n=Number(localStorage.getItem('yessiDay')||1)+d;n=Math.max(1,Math.min(90,n));localStorage.setItem('yessiDay',n);renderToday()};
function renderMetrics(){let rows=state.metrics.map((m,i)=>`<tr><td>${i+1}</td>${['followers','reach','shares','saves','follows'].map(k=>`<td><input value="${esc(m[k]||'')}" oninput="metric(${i},'${k}',this.value)"></td>`).join('')}<td><button onclick="delMetric(${i})">×</button></td></tr>`).join('');document.getElementById('metricsTable').innerHTML=`<table><thead><tr><th>Semana</th><th>Seguidores</th><th>Alcance</th><th>Compartidos</th><th>Guardados</th><th>Follows</th><th></th></tr></thead><tbody>${rows||'<tr><td colspan="7">Añade tu primera semana.</td></tr>'}</tbody></table>`}
window.metric=(i,k,v)=>{state.metrics[i][k]=v;save()};window.delMetric=i=>{state.metrics.splice(i,1);save();renderMetrics()};document.getElementById('addMetric').onclick=()=>{state.metrics.push({});save();renderMetrics()};
document.getElementById('exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify({state,day:localStorage.getItem('yessiDay')||1},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='yessi-antipanico-respaldo.json';a.click();URL.revokeObjectURL(a.href)};
document.getElementById('importFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{try{const d=JSON.parse(rd.result);state=d.state||d;save();if(d.day)localStorage.setItem('yessiDay',d.day);renderAll();toast('Respaldo importado')}catch{alert('Archivo inválido')}};rd.readAsText(f)};
document.getElementById('resetBtn').onclick=()=>{if(confirm('¿Borrar todo tu progreso local?')){localStorage.removeItem(KEY);localStorage.removeItem('yessiDay');location.reload()}};
function renderAll(){renderReels();renderCalendar();renderToday();renderMetrics()}renderAll();
if('serviceWorker' in navigator && location.protocol.startsWith('http')) navigator.serviceWorker.register('sw.js');
